import {useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,BadgeCheck,CheckCircle2,Clock,Languages,MapPin,ShoppingBag,Truck,Wheat} from 'lucide-react';
import {demoBuyers} from '../demo';
import {apiPost} from '../services/api';
import {getLang,setLang,languages,ui,Lang} from '../i18n';

type Crop={key:string;en:string;hi:string;te:string;mr:string;base:number};
const crops:Crop[]=[
 {key:'onion',en:'Onion',hi:'प्याज़',te:'ఉల్లిపాయ',mr:'कांदा',base:1850},
 {key:'soybean',en:'Soybean',hi:'सोयाबीन',te:'సోయాబీన్',mr:'सोयाबीन',base:2750},
 {key:'cotton',en:'Cotton',hi:'कपास',te:'పత్తి',mr:'कापूस',base:6800},
 {key:'wheat',en:'Wheat',hi:'गेहूं',te:'గోధుమ',mr:'गहू',base:2250},
 {key:'tur',en:'Tur (Arhar)',hi:'तुअर (अरहर)',te:'కందులు',mr:'तूर (हरभरा)',base:7100}
];
const locations=[
 {key:'sehore',en:'Sehore, MP',hi:'सीहोर, म.प्र.',te:'సీహోర్, మధ్యప్రదేశ్',mr:'सिहोर, म.प्र.'},
 {key:'indore',en:'Indore, MP',hi:'इंदौर, म.प्र.',te:'ఇండోర్, మధ్యప్రదేశ్',mr:'इंदूर, म.प्र.'},
 {key:'bhopal',en:'Bhopal, MP',hi:'भोपाल, म.प्र.',te:'భోపాల్, మధ్యప్రదేశ్',mr:'भोपाळ, म.प्र.'}
];
const text:Record<Lang,{brand:string;tag:string;steps:string[];details:string;crop:string;qty:string;location:string;next:string;back:string;priceTitle:string;today:string;trend:string;advisory:string;advisoryText:string;buyersTitle:string;verified:string;offering:string;select:string;profitTitle:string;transport:string;production:string;net:string;total:string;confirm:string;dealTitle:string;dealWith:string;payment:string;grievance:string;newSale:string;quintals:string;saving:string}>={
 en:{brand:'KISSAN SATHI',tag:'Farm-gate price intelligence & verified buyer linkage',steps:['Details','Prices','Buyers','Profit','Deal'],details:'Tell us about your crop',crop:'Crop',qty:'Quantity (quintals)',location:'Your location',next:'See prices near you',back:'Back',priceTitle:'Price intelligence',today:"Today's mandi price",trend:'7-day price trend',advisory:'Sell-window advisory',advisoryText:'The recent trend is positive in this demo. Compare the full net realization before deciding.',buyersTitle:'Verified buyers for your lot',verified:'Verified',offering:'offering',select:'Select & calculate profit',profitTitle:'Transport cost vs profit',transport:'Estimated transport cost',production:'Production cost / qtl',net:'Net profit / qtl',total:'Total profit for your lot',confirm:'Confirm this deal',dealTitle:'Deal confirmed',dealWith:'Deal confirmed with',payment:'Payment status',grievance:'Raise a grievance',newSale:'Start a new sale',quintals:'quintals',saving:'Saving…'},
 hi:{brand:'किसानसाथी',tag:'खेत-द्वार मूल्य जानकारी और सत्यापित खरीदार संपर्क',steps:['विवरण','मूल्य','खरीदार','मुनाफा','सौदा'],details:'अपनी फसल के बारे में बताएं',crop:'फसल',qty:'मात्रा (क्विंटल)',location:'आपका स्थान',next:'अपने पास के मूल्य देखें',back:'वापस',priceTitle:'मूल्य जानकारी',today:'आज का मंडी भाव',trend:'7-दिन का मूल्य रुझान',advisory:'बिक्री-समय सलाह',advisoryText:'इस डेमो में हाल का रुझान सकारात्मक है। निर्णय से पहले पूरा शुद्ध मूल्य देखें।',buyersTitle:'आपके लॉट के लिए सत्यापित खरीदार',verified:'सत्यापित',offering:'प्रस्ताव',select:'चुनें और मुनाफा निकालें',profitTitle:'परिवहन लागत बनाम मुनाफा',transport:'अनुमानित परिवहन लागत',production:'उत्पादन लागत / क्विंटल',net:'प्रति क्विंटल शुद्ध मुनाफा',total:'आपके पूरे माल पर कुल मुनाफा',confirm:'यह सौदा पक्का करें',dealTitle:'सौदा पक्का हुआ',dealWith:'सौदा पक्का हुआ',payment:'भुगतान की स्थिति',grievance:'शिकायत दर्ज करें',newSale:'नई बिक्री शुरू करें',quintals:'क्विंटल',saving:'सहेजा जा रहा है…'},
 te:{brand:'కిసాన్ సాథి',tag:'పొలం వద్ద ధర సమాచారం & ధృవీకరించిన కొనుగోలుదారుల అనుసంధానం',steps:['వివరాలు','ధరలు','కొనుగోలుదారులు','లాభం','ఒప్పందం'],details:'మీ పంట వివరాలు చెప్పండి',crop:'పంట',qty:'పరిమాణం (క్వింటాళ్లు)',location:'మీ ప్రాంతం',next:'దగ్గర ధరలు చూడండి',back:'వెనుకకు',priceTitle:'ధర సమాచారం',today:'ఈరోజు మండీ ధర',trend:'7 రోజుల ధర ధోరణి',advisory:'విక్రయ సమయ సూచన',advisoryText:'ఈ డెమోలో ఇటీవలి ధోరణి సానుకూలంగా ఉంది. నిర్ణయం ముందు పూర్తి నికర ఆదాయాన్ని చూడండి.',buyersTitle:'మీ లాట్‌కు ధృవీకరించిన కొనుగోలుదారులు',verified:'ధృవీకరించబడింది',offering:'ఆఫర్',select:'ఎంచుకుని లాభం లెక్కించండి',profitTitle:'రవాణా ఖర్చు vs లాభం',transport:'అంచనా రవాణా ఖర్చు',production:'ఉత్పత్తి ఖర్చు / క్వింటాల్',net:'నికర లాభం / క్వింటాల్',total:'మీ మొత్తం లాట్ లాభం',confirm:'ఈ ఒప్పందాన్ని నిర్ధారించండి',dealTitle:'ఒప్పందం నిర్ధారించబడింది',dealWith:'ఒప్పందం:',payment:'చెల్లింపు స్థితి',grievance:'ఫిర్యాదు నమోదు చేయండి',newSale:'కొత్త అమ్మకం ప్రారంభించండి',quintals:'క్వింటాళ్లు',saving:'సేవ్ అవుతోంది…'},
 mr:{brand:'किसान साथी',tag:'शेतमालाच्या ठिकाणी किंमत माहिती आणि सत्यापित खरेदीदार जोडणी',steps:['तपशील','किंमती','खरेदीदार','नफा','व्यवहार'],details:'तुमच्या पिकाची माहिती द्या',crop:'पीक',qty:'प्रमाण (क्विंटल)',location:'तुमचे ठिकाण',next:'जवळच्या किंमती पहा',back:'मागे',priceTitle:'किंमत माहिती',today:'आजचा मंडी भाव',trend:'7 दिवसांचा किंमत कल',advisory:'विक्री वेळ सल्ला',advisoryText:'या डेमोमध्ये अलीकडचा कल सकारात्मक आहे. निर्णयापूर्वी संपूर्ण निव्वळ मिळकत तपासा.',buyersTitle:'तुमच्या लॉटसाठी सत्यापित खरेदीदार',verified:'सत्यापित',offering:'ऑफर',select:'निवडा आणि नफा मोजा',profitTitle:'वाहतूक खर्च विरुद्ध नफा',transport:'अंदाजे वाहतूक खर्च',production:'उत्पादन खर्च / क्विंटल',net:'निव्वळ नफा / क्विंटल',total:'तुमच्या संपूर्ण लॉटचा नफा',confirm:'हा व्यवहार निश्चित करा',dealTitle:'व्यवहार निश्चित झाला',dealWith:'व्यवहार:',payment:'देयक स्थिती',grievance:'तक्रार नोंदवा',newSale:'नवीन विक्री सुरू करा',quintals:'क्विंटल',saving:'सेव्ह होत आहे…'}
};

function money(n:number){return `₹${Math.round(n).toLocaleString('en-IN')}`;}
function priceSeries(base:number){return [0,1,2,3,4,5,6].map(i=>Math.round(base*(0.94+i*0.01+(i%2?0.003:0))));}

export default function SellCrop(){
 const [lang,setCurrentLang]=useState<Lang>(getLang()); const t=text[lang];
 const [step,setStep]=useState(0); const [crop,setCrop]=useState('soybean'); const [qty,setQty]=useState(20); const [location,setLocation]=useState('sehore');
 const [buyerId,setBuyerId]=useState<string|null>(null); const [transport,setTransport]=useState(300); const [prodCost,setProdCost]=useState(1200); const [confirmed,setConfirmed]=useState(false); const [saving,setSaving]=useState(false);
 const cropObj=crops.find(c=>c.key===crop)||crops[1]; const series=useMemo(()=>priceSeries(cropObj.base),[cropObj]); const today=series[series.length-1];
 const buyers=useMemo(()=>demoBuyers.map((b,i)=>({id:b.id,name:b.name,location:b.location,price:Math.round(today*(i===0?1.06:i===1?1.03:1.09)),verified:true,distance:i===0?22:i===1?8:64})),[today]);
 const selected=buyers.find(b=>b.id===buyerId)||null; const net=selected?selected.price-prodCost-transport/qty:0; const total=net*qty;
 const next=()=>setStep(s=>Math.min(4,s+1)); const back=()=>setStep(s=>Math.max(0,s-1));
 const confirm=async()=>{if(!selected)return; setSaving(true); try{await apiPost('/farmer/lots',{crop:cropObj.en,quantityQtl:qty,quality:'FAQ',location:locations.find(l=>l.key===location)?.en||'Sehore, MP',availableDate:'2026-09-18',priceAsk:selected.price}); await apiPost('/deals',{lotId:'lot1',buyerId:selected.id,quantityQtl:qty,pricePerQtl:selected.price});}catch{} finally{setSaving(false);setConfirmed(true);setStep(4);}};
 const restart=()=>{setStep(0);setBuyerId(null);setConfirmed(false);};
 return <div className="sell-flow card">
   <div className="sell-head"><div><div className="sell-brand">{t.brand}</div><div className="sell-tag">{t.tag}</div></div><button className="lang-switch" onClick={()=>{const i=languages.findIndex(l=>l.key===lang); const next=languages[(i+1)%languages.length].key; setLang(next); setCurrentLang(next)}}><Languages size={15}/> {languages.find(l=>l.key===lang)?.native||'English'}</button></div>
   <div className="sell-stepper">{t.steps.map((s,i)=><div className="sell-step-wrap" key={s}><div className={`sell-step ${i<=step?'done':''}`}>{i<step?<CheckCircle2 size={16}/>:i+1}</div><span className={i===step?'current':''}>{s}</span>{i<t.steps.length-1&&<div className={`sell-line ${i<step?'done':''}`}/>}</div>)}</div>
   {step===0&&<section><h2><Wheat size={21}/>{t.details}</h2><label>{t.crop}</label><div className="sell-pills">{crops.map(c=><button key={c.key} className={crop===c.key?'selected':''} onClick={()=>setCrop(c.key)}><Wheat size={15}/>{c[lang]}</button>)}</div><label>{t.qty}</label><input className="sell-range" type="range" min="1" max="100" value={qty} onChange={e=>setQty(+e.target.value)}/><strong className="sell-qty">{qty} {t.quintals}</strong><label>{t.location}</label><div className="sell-pills">{locations.map(l=><button key={l.key} className={location===l.key?'selected':''} onClick={()=>setLocation(l.key)}><MapPin size={15}/>{l[lang]}</button>)}</div><button className="button" onClick={next}>{t.next}<ArrowRight size={16}/></button></section>}
   {step===1&&<section><h2><ShoppingBag size={21}/>{t.priceTitle}</h2><div className="sell-price-row"><div><span>{t.today}</span><strong>{money(today)}<small>/qtl</small></strong></div><div className="sell-bars">{series.map((v,i)=><div key={i} style={{height:`${30+((v-Math.min(...series))/(Math.max(...series)-Math.min(...series)||1))*70}%`}} title={money(v)}/>)}</div></div><div className="sell-advisory"><Clock size={17}/><div><strong>{t.advisory}</strong><p>{t.advisoryText}</p></div></div><div className="sell-actions"><button className="button ghost-button" onClick={back}><ArrowLeft size={16}/>{t.back}</button><button className="button" onClick={next}>{t.steps[2]}<ArrowRight size={16}/></button></div></section>}
   {step===2&&<section><h2><BadgeCheck size={21}/>{t.buyersTitle}</h2><div className="sell-buyers">{buyers.map(b=><button key={b.id} className={`sell-buyer ${buyerId===b.id?'selected':''}`} onClick={()=>setBuyerId(b.id)}><div><strong>{b.name}</strong><span>{b.location} · {b.distance} km</span></div><div><b>{money(b.price)}/qtl</b><small>{b.verified&&t.verified}</small></div></button>)}</div><div className="sell-actions"><button className="button ghost-button" onClick={back}><ArrowLeft size={16}/>{t.back}</button><button className="button" disabled={!buyerId} onClick={next}>{t.select}<ArrowRight size={16}/></button></div></section>}
   {step===3&&<section><h2><Truck size={21}/>{t.profitTitle}</h2><div className="sell-controls"><label>{t.transport}<b>{money(transport)}</b><input type="range" min="100" max="1500" step="50" value={transport} onChange={e=>setTransport(+e.target.value)}/></label><label>{t.production}<b>{money(prodCost)}</b><input type="range" min="500" max="2500" step="50" value={prodCost} onChange={e=>setProdCost(+e.target.value)}/></label></div><div className="sell-profit"><div><span>{t.net}</span><strong>{money(net)}</strong></div><div><span>{t.total}</span><strong>{money(total)}</strong></div></div><div className="sell-note">{selected?.name} offers {money(selected?.price||0)}/qtl. Transport is spread across your {qty} qtl lot.</div><div className="sell-actions"><button className="button ghost-button" onClick={back}><ArrowLeft size={16}/>{t.back}</button><button className="button" disabled={!selected} onClick={confirm}>{saving?t.saving:t.confirm}<ArrowRight size={16}/></button></div></section>}
   {step===4&&<section className="sell-confirm"><div className="confirm-icon"><CheckCircle2 size={32}/></div><h2>{t.dealTitle}</h2>{confirmed&&selected?<><p>{t.dealWith} <strong>{selected.name}</strong></p><div className="confirm-grid"><div><span>{t.qty}</span><strong>{qty} qtl</strong></div><div><span>Price / qtl</span><strong>{money(selected.price)}</strong></div><div><span>{t.total}</span><strong>{money(total)}</strong></div><div><span>{t.payment}</span><strong>Demo escrow</strong></div></div><div className="tracking"><span>✓ Lot created</span><span>✓ Quality grading</span><span>✓ Payment in escrow</span><span>○ Payment released</span></div><button className="button ghost-button" onClick={restart}>{t.newSale}</button></>:<p>Choose a buyer and confirm the deal to complete this demo flow.</p>}</section>}
 </div>;
}
