import {markets,marketHistory,transporters,warehouses,buyers,lots,Offer,offers,demoFarmer} from './data.js';
export function calcProfit(input:{quantityQtl:number;marketId:string;crop:string;poolFarmers?:number;storeDays?:number;offerPrice?:number}){
 const m=markets.find(x=>x.id===input.marketId)||markets[0]; const q=Math.max(input.quantityQtl,1); const pool=Math.max(input.poolFarmers||1,1); const distance=Math.max(m.distanceKm,1);
 const gross=q*m.price; const vehicleFixed=6500; const variablePerKm=Math.min(42,38+distance/250); const transport=vehicleFixed/pool + distance*(variablePerKm)*(q*100)/100; const loading=120*q, unloading=100*q, toll=distance>200?Math.round(distance*.55):0; const commission=gross*m.commissionPct/100; const storage=(input.storeDays||0)*m.storagePerQtl*q; const packaging=42*q, handling=35*q, wastage=gross*(input.storeDays?0.025*(input.storeDays/5):0.012)+gross*(distance>500?.025:0.01); const net=gross-transport-loading-unloading-toll-commission-storage-packaging-handling-wastage;
 const local=2750*q-(6500/1)-120*q-100*q-2750*q*.013-42*q-35*q-2750*q*.012; const risk=Math.min(95,Math.round(20+distance/25+(input.crop==='Tomato'?22:8)+(input.storeDays||0)*4));
 return {market:m,quantityQtl:q,gross,transport,loading,unloading,toll,commission,storage,packaging,handling,expectedWastage:wastage,otherCosts:0,netRealization:net,netPerQtl:net/q,localNet:local,deltaVsLocal:net-local,risk,breakEvenQuantityQtl:Math.max(1,Math.ceil(vehicleFixed/(Math.max(1,m.price-2750)*100 - distance*1.25 - 220))),profitable:net>local};
}
export function recommendation(){
 const m=markets.slice().sort((a,b)=>calcProfit({quantityQtl:20,marketId:b.id,crop:'Soybean',poolFarmers:6}).netPerQtl-calcProfit({quantityQtl:20,marketId:a.id,crop:'Soybean',poolFarmers:6}).netPerQtl)[0];
 const p=calcProfit({quantityQtl:20,marketId:m.id,crop:'Soybean',poolFarmers:6});
 return {action:p.netPerQtl>p.localNet/20?'TRANSPORT + POOL':'SELL LOCAL',market:m,expectedNetPerQtl:Math.round(p.netPerQtl),expectedTotal:Math.round(p.netRealization),confidence:78,regime:'RISING',reasons:[`Destination price ₹${m.price.toLocaleString('en-IN')}/qtl`,`${m.demand} demand with lower arrivals`,`Pooling with 6 farmers reduces fixed transport cost`,`Net realization is ₹${Math.round(p.netPerQtl).toLocaleString('en-IN')}/qtl after modeled costs`,`Risk ${p.risk}/100; verify weather before dispatch`]};
}
export function buyerMatches(lotId:string){const lot=lots.find(l=>l.id===lotId)||lots[0]; return buyers.map(b=>{const crop=b.crop===lot.crop?1:0,qty=Math.min(1,b.requiredQtyQtl/Math.max(lot.quantityQtl,1)),quality=b.quality===lot.quality?1:.75,trust=b.trust/100,region=b.state===demoFarmer.state?1:.75,score=Math.round((crop*.32+qty*.18+quality*.15+trust*.15+region*.1+(b.pickup?.1:0))*100); return {...b,matchScore:score,breakdown:{crop,quantity:qty,quality,trust,region,pickup:b.pickup}}}).filter(x=>x.crop===lot.crop).sort((a,b)=>b.matchScore-a.matchScore).slice(0,8);}
export function history(marketId:string){const m=markets.find(x=>x.id===marketId)||markets[0]; return marketHistory(m);}
export function forecast(marketId:string){const h=history(marketId); const last=h.at(-1)!.price; return [1,2,3,4,5,6,7].map(d=>({day:d,expected:Math.round(last*(1+.006*d)),low:Math.round(last*(.985+.002*d)),high:Math.round(last*(1.02+.006*d))}));}
export function opportunityStates(){return markets.map(m=>({state:m.state,city:m.city,demandScore:m.demand==='Very High'?95:m.demand==='High'?82:m.demand==='Medium'?62:45,price:m.price,arrivals:m.arrival,signal:m.trend>2?'Rising demand':'Balanced'})).sort((a,b)=>b.demandScore-a.demandScore).slice(0,8)}
export function transportQuotes(distance:number,quantity:number){return transporters.filter(t=>t.available && t.capacityQtl>=quantity).slice(0,8).map(t=>({...t,quote:Math.round(t.fixedCost+distance*t.pricePerKm)})).sort((a,b)=>a.quote-b.quote);}
export function storeScenario(marketId:string,qty:number,days:number){const p=calcProfit({quantityQtl:qty,marketId,crop:'Soybean',storeDays:days}); const future=p.market.price*(1+.006*days); return {...p,projectedPrice:future,projectedNet:p.netRealization+(future-p.market.price)*qty,storeDecision:future-p.storage/days>2750?'STORE':'SELL NOW'};}
