import express from 'express'; import cors from 'cors'; import helmet from 'helmet'; import auth from './routes/auth.js'; import {requireAuth,requireRole} from './middleware/auth.js'; import {markets,marketHistory,demoFarmer,lots,buyers,offers,deals,transporters,warehouses,notifications,farmers} from './data.js';
import {calcProfit,recommendation,buyerMatches,history,forecast,opportunityStates,transportQuotes,storeScenario} from './engine.js';
import {env} from './config/env.js';
const app=express();app.use(helmet());app.use(cors({origin:env.CORS_ORIGIN==='*'?true:env.CORS_ORIGIN}));app.use(express.json({limit:'2mb'}));
app.get('/api',(_,res)=>res.json({name:'KISSAN SATHI API',version:'2.0.0',mode:'demo',demoData:true}));
app.get('/health',(_,res)=>res.json({ok:true,service:'server',db:{ok:true,mode:'demo-fallback'},ai:{ok:true,mode:'rule-backed-demo'}}));
app.use('/api/auth',auth);
app.get('/api/markets',(_,res)=>res.json({data:markets})); app.get('/api/markets/:id', (req,res)=>{const m=markets.find(x=>x.id===req.params.id); if(!m)return res.sendStatus(404);res.json(m)});
app.get('/api/markets/:id/prices',(req,res)=>res.json({data:history(req.params.id)})); app.get('/api/markets/:id/forecast',(req,res)=>res.json({data:forecast(req.params.id),model:'demo LSTM-style sequence forecaster'}));
app.get('/api/forecast',(req,res)=>res.json({data:forecast(String(req.query.marketId||'m1')),confidence:0.78}));
app.get('/api/market-opportunities',(_,res)=>res.json({data:opportunityStates()}));
app.get('/api/farmer/dashboard',(_,res)=>res.json({farmer:{id:'f1',name:'Ramesh Kumar',crop:'Soybean',quantityQtl:20,location:'Sehore'},recommendation:recommendation()}));
app.get('/api/farmer/opportunities',(_,res)=>res.json({data:opportunityStates()}));
app.get('/api/farmer/transport',(_,res)=>res.json({data:transporters}));
app.get('/api/farmer/storage',(_,res)=>res.json({data:warehouses}));
app.get('/api/farmer/deals',(_,res)=>res.json({data:deals}));
app.get('/api/farmer/payments',(_,res)=>res.json({data:deals.map(d=>({dealId:d.id,amount:d.total,status:'Pending'}))}));
app.get('/api/farmer/notifications',(_,res)=>res.json({data:notifications.farmer}));
app.get('/api/buyer/dashboard',(_,res)=>res.json({activeRequirements:3,matchedLots:18,incomingOffers:4,onTimeSuppliers:92}));
app.get('/api/buyer/notifications',(_,res)=>res.json({data:notifications.buyer}));
app.post('/api/profit/calculate',(req,res)=>res.json(calcProfit(req.body)));
app.post('/api/transport/calculate',(req,res)=>{const q=Number(req.body.quantityQtl||20),d=Number(req.body.distanceKm||280);res.json({distanceKm:d,quantityQtl:q,quotes:transportQuotes(d,q),minimumEconomicQuantityQtl:Math.ceil(6500/(Math.max(1,Number(req.body.priceAdvantagePerQtl||160))*1)),poolRecommended:q<40})});
app.get('/api/transport/vendors',(req,res)=>res.json({data:transporters})); app.post('/api/transport/requests',(req,res)=>res.status(201).json({id:`tr-${Date.now()}`,status:'Open',...req.body})); app.post('/api/transport/bids',(req,res)=>res.status(201).json({id:`bid-${Date.now()}`,status:'Submitted',...req.body}));
app.get('/api/storage',(_,res)=>res.json({data:warehouses})); app.post('/api/storage/book',(req,res)=>res.status(201).json({id:`sb-${Date.now()}`,status:'Reserved',...req.body}));
app.get('/api/farmer/lots',(req,res)=>res.json({data:lots.filter(l=>l.farmerId==='f1')})); app.post('/api/farmer/lots',(req,res)=>{const x={id:`lot-${Date.now()}`,farmerId:'f1',farmerName:'Ramesh Kumar',status:'Available',...req.body};lots.unshift(x as any);res.status(201).json(x)});
app.get('/api/farmer/recommendation',(_,res)=>res.json(recommendation()));
app.get('/api/buyers',(req,res)=>res.json({data:buyers})); app.get('/api/farmer/buyers',(req,res)=>res.json({data:buyers})); app.get('/api/farmer/buyer/:id',(req,res)=>res.json(buyers.find(b=>b.id===req.params.id)||buyers[0]));
app.get('/api/buyer/farmers',(req,res)=>res.json({data:farmers.slice(0,15)})); app.get('/api/buyer/lots',(req,res)=>res.json({data:lots.filter(l=>l.status==='Available')}));
app.post('/api/buyer/requirements',(req,res)=>res.status(201).json({id:`req-${Date.now()}`,status:'Active',...req.body})); app.get('/api/buyer/requirements',(_,res)=>res.json({data:[{id:'req1',crop:'Soybean',qtyQtl:100,quality:'FAQ',maxPrice:3100,location:'Nagpur',requiredDate:'2026-09-20',status:'Active'}]}));
app.get('/api/buyer/matches',(req,res)=>res.json({data:buyerMatches(String(req.query.lotId||'lot1'))}));
app.get('/api/buyer/offers',(req,res)=>res.json({data:offers}));app.post('/api/offers',(req,res)=>{const o={id:`off-${Date.now()}`,status:'Pending',...req.body};offers.push(o as any);res.status(201).json(o)});
app.get('/api/deals',(_,res)=>res.json({data:deals})); app.get('/api/deals/:id',(req,res)=>{const d=deals.find(x=>x.id===req.params.id); if(!d)return res.sendStatus(404);res.json(d)});
app.post('/api/deals',(req,res)=>{const b=buyers.find(x=>x.id===req.body.buyerId)||buyers[0];const l=lots.find(x=>x.id===req.body.lotId)||lots[0];const id=`deal-${Date.now()}`;const d={id,lotId:l.id,buyerId:b.id,buyerName:b.name,farmerId:l.farmerId,farmerName:l.farmerName,crop:l.crop,quantityQtl:req.body.quantityQtl||l.quantityQtl,pricePerQtl:req.body.pricePerQtl||b.offeredPrice,total:(req.body.quantityQtl||l.quantityQtl)*(req.body.pricePerQtl||b.offeredPrice),status:'Accepted',events:[{status:'Accepted',date:new Date().toISOString(),note:'Offer accepted in demo'}]};deals.push(d);res.status(201).json(d)});
app.put('/api/deals/:id/status',(req,res)=>{const d=deals.find(x=>x.id===req.params.id);if(!d)return res.sendStatus(404);d.status=req.body.status;d.events.push({status:d.status,date:new Date().toISOString(),note:req.body.note||''});res.json(d)});
app.get('/api/payments',(_,res)=>res.json({data:deals.map(d=>({dealId:d.id,amount:d.total,status:'Pending',reference:`DEMO-${d.id}`}))})); app.post('/api/payments/:id/status',(req,res)=>res.json({dealId:req.params.id,status:req.body.status||'Confirmed',reference:`DEMO-${req.params.id}`}));
app.post('/api/simulator',(req,res)=>{const qty=Number(req.body.quantityQtl||20);const marketId=String(req.body.marketId||'m4');const pool=Number(req.body.poolFarmers||1);const days=Number(req.body.storeDays||0);res.json({current:calcProfit({quantityQtl:qty,marketId:'m1',crop:'Soybean',poolFarmers:1}),scenarios:[calcProfit({quantityQtl:qty,marketId:marketId,crop:'Soybean',poolFarmers:pool}),calcProfit({quantityQtl:qty,marketId:'m1',crop:'Soybean',storeDays:days}),calcProfit({quantityQtl:qty,marketId:'m4',crop:'Soybean',poolFarmers:6})].map((x,i)=>({...x,label:['Selected market','Store / wait','Pool to destination'][i]}))})});
app.post('/api/grievances',(req,res)=>res.status(201).json({id:`g-${Date.now()}`,status:'Submitted',createdAt:new Date().toISOString(),...req.body}));app.get('/api/grievances',(_,res)=>res.json({data:[]}));
app.get('/api/notifications',(req,res)=>res.json({data:notifications.farmer}));
app.get('/api/profile',(req,res)=>res.json(demoFarmer));
app.use((err:any,_req:any,res:any,_next:any)=>res.status(err?.name==='ZodError'?400:500).json({error:err?.message||'Internal server error'}));
app.listen(env.PORT,()=>console.log(`KISSAN SATHI server listening on ${env.PORT}`));
